name: Release

on:
  push:
    branches:
      - main
      - beta
      # - '+([0-9])?(.{+([0-9]),x}).x'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4
        with:
          persist-credentials: false

      - name: Use Node.js LTS
        uses: actions/setup-node@8f152de45cc393bb48ce5d89d36b731f54556e65 # v4
        with:
          node-version: 'lts/*'
          cache: npm

      - name: Install packages
        run: npm ci

      - name: Audit npm signatures
        run: npm audit signatures

      - name: Lock project
        run: npm run lock

      - name: Run Semantic Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
